package by.bsuir.gerasimovich.logic;


public enum CommandName {
    NO_SUCH_COMMAND,DO_LIST_OF_ALL_FILTER,
    DO_LIST_OF_ALL_WITH_SORT,DO_SEARCH,
    OPERATION_WITH_MODEL,OPERATION_WITH_BRANDS,
    OPERATION_WITH_AGENT,GENERATION_REPORT,
    ENTER_NEW_ITEMS,REMOVE_ITEMS
}
